Repository zip-up/zipup-frontend, pull requests merged in 2024-06, with the labels that each got.

#81 [#80] Bugfix: 마이페이지 관련 버그 수정
  src/components/Accordion/index.tsx
  src/components/Accordion/styles.ts
  src/components/Card/index.tsx
  src/components/Card/styles.ts
  src/components/Footer/index.tsx
  src/components/MyFundings/styles.ts
  src/constants/faqs.ts
  src/pages/faq/index.page.tsx
  src/pages/faq/styles.ts
  src/pages/funding/create/1/index.page.tsx
  src/pages/index.page.tsx
  src/pages/mypage/index.page.tsx
  src/pages/mypage/styles.ts
  src/types/funding.ts
Labels: 🐛 BugFix

#88 [#83] Fix: 결제 및 탈퇴 라우팅 이슈 및 로그아웃 기능 구현
  package.json
  pnpm-lock.yaml
  src/components/Layout/NoticePageLayout/index.tsx
  src/components/common/Tabs/index.tsx
  src/components/common/Tabs/style.ts
  src/contexts/ReactQueryContext.tsx
  src/hooks/queries/useAuth.ts
  src/pages/_app.page.tsx
  src/pages/funding/[id]/participate/index.page.tsx
  src/pages/funding/[id]/payment/fail.page.tsx
  src/pages/invite/[id]/index.page.tsx
  src/pages/mypage/index.page.tsx
  src/pages/mypage/payinfo/index.page.tsx
  src/pages/mypage/payinfo/styles.ts
  src/pages/mypage/withdrawal/fail.page.tsx
  src/pages/mypage/withdrawal/index.page.tsx
Labels: 🐛 BugFix, ✨ Feature

#92 [#87] Feature: 홈페이지 및 펀딩 개설 페이지 집꾸템 api 연결, 기능 및 디자인 이슈 수정
  src/components/Card/index.tsx
  src/components/Card/styles.ts
  src/components/FundingStatusBox/index.tsx
  src/hooks/queries/useFundingList.ts
  src/pages/index.page.tsx
Labels: 🐛 BugFix, ✨ Feature

#95 [#89] Feature: 가상계좌 정보 ui 및 회원 탈퇴 안내 문구 추가
  src/components/PaymentCard/index.tsx
  src/constants/bank.ts
  src/constants/notice.ts
  src/pages/mypage/payinfo/index.page.tsx
  src/pages/mypage/withdrawal/styles.ts
  src/types/funding.ts
Labels: ✨ Feature
