Repository zip-up/zipup-frontend, pull requests merged in 2024-03, with the labels that each got.

#2 [#1] Feature: 레이아웃 구현
  .github/ISSUE_TEMPLATE/feat.md
  package.json
  pnpm-lock.yaml
  src/components/Layout/index.tsx
  src/components/Layout/styles.ts
  src/pages/_app.tsx
  src/styles/globals.css
Labels: ✨ Feature

#4 [#3] Chore: 컬러 시스템 및 폰트 적용
  .github/PULL_REQUEST_TEMPLATE.md
  panda.config.ts
  src/asset/fonts/Pretendard-Bold.woff
  src/asset/fonts/Pretendard-Regular.woff
  src/asset/fonts/Pretendard-SemiBold.woff
  src/pages/index.tsx
  src/styles/font.ts
Labels: ⚙️ Chore

#6 [#5] Chore: Vercel 배포를 위한 작업
  .github/workflows/deploy.yml
  build.sh
Labels: ⚙️ Chore

#9 [#7] Feature: 로그인 페이지 구현
  .gitignore
  custom.d.ts
  next.config.js
  package.json
  panda.config.ts
  pnpm-lock.yaml
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/login-button.svg
  src/assets/logo.svg
  src/components/Layout/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/styles.ts
  src/components/common/Modal/index.tsx
  src/components/common/Modal/styles.ts
  src/components/modals/LoginModal/index.tsx
  src/components/modals/LoginModal/styles.ts
  src/pages/index.tsx
  src/pages/kakao/callback/index.tsx
  src/pages/style.ts
  src/styles/font.ts
  tsconfig.json
  webpack.config.ts
Labels: ✨ Feature

#11 [#8] Feature: 결제 위젯 연동, 성공 및 에러 처리
  package.json
  pnpm-lock.yaml
  src/components/Layout/styles.ts
  src/hooks/queries/usePayment.ts
  src/pages/funding/[id]/index.tsx
  src/pages/funding/[id]/payment/fail.tsx
  src/pages/funding/[id]/payment/index.tsx
  src/pages/funding/[id]/payment/success.tsx
  src/types/env.d.ts
  tsconfig.json
Labels: ✨ Feature

#12 [#10] Feature: 로그인 기능 api 연결
  src/components/modals/LoginModal/index.tsx
  src/pages/index.tsx
  src/pages/kakao/callback/index.tsx
Labels: ✨ Feature

#16 [#13] Feature: 펀딩 개설 UI 구현
  package.json
  pnpm-lock.yaml
  src/assets/after.svg
  src/assets/back.svg
  src/assets/before.svg
  src/assets/calendar_month.svg
  src/assets/cancel-icon.svg
  src/assets/checked.svg
  src/assets/gift-icon.svg
  src/assets/login-icon.svg
  src/assets/open.svg
  src/assets/search.svg
  src/assets/unchecked.svg
  src/components/Calendar/index.tsx
  src/components/Calendar/styles.ts
  src/components/common/Button/index.tsx
  src/components/common/Button/styles.ts
  src/components/common/Header/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Modal/styles.ts
  src/components/modals/AddressModal/index.tsx
  src/components/modals/LoginModal/index.tsx
  src/components/modals/ModalWithIcon/index.tsx
  src/components/modals/ModalWithIcon/styles.ts
  src/pages/fund/create/1/index.tsx
  src/pages/fund/create/2/index.tsx
  src/pages/fund/create/3/index.tsx
  src/pages/fund/create/4/index.tsx
  src/pages/fund/create/styles.ts
  src/pages/index.tsx
  src/pages/style.ts
  src/styles/globals.css
Labels: ✨ Feature

#18 [#15] Feature: 펀딩 상세 페이지 UI 구현 및 StatusTag 공통 컴포넌트 구현
  src/api/index.ts
  src/assets/icons/back.svg
  src/assets/images/default_present.svg
  src/assets/images/login-button.svg
  src/assets/images/logo.svg
  src/components/MessageList/MessageBox/index.tsx
  src/components/MessageList/MessageBox/styles.ts
  src/components/MessageList/index.tsx
  src/components/MessageList/styles.ts
  src/components/common/Button/index.tsx
  src/components/common/Button/styles.ts
  src/components/common/Header/styles.ts
  src/components/common/Modal/styles.ts
  src/components/common/StatusTag/index.tsx
  src/components/common/StatusTag/styles.ts
  src/components/modals/ModalWithIcon/styles.ts
  src/contexts/ReactQueryContext.tsx
  src/hooks/queries/useFunding.ts
  src/pages/funding/[id]/index.tsx
  src/pages/funding/[id]/styles.ts
  src/pages/index.tsx
  src/types/funding.ts
  tsconfig.json
Labels: ✨ Feature

#23 [#19] Feature: 초대 페이지 UI 작업
  public/image_2.svg
  src/components/FundingStatusBox/index.tsx
  src/components/FundingStatusBox/styles.ts
  src/components/common/StatusTag/styles.ts
  src/pages/funding/[id]/index.tsx
  src/pages/funding/[id]/styles.ts
  src/pages/invite/[id]/index.tsx
  src/pages/invite/[id]/styles.ts
Labels: ✨ Feature

#25 [#20] Feature: 마이페이지 구현
  src/assets/back.svg
  src/assets/icons/after.svg
  src/assets/icons/before.svg
  src/assets/icons/calendar_month.svg
  src/assets/icons/cancel-icon.svg
  src/assets/icons/checked.svg
  src/assets/icons/exit.svg
  src/assets/icons/gift-icon.svg
  src/assets/icons/gift-image.svg
  src/assets/icons/go.svg
  src/assets/icons/login-icon.svg
  src/assets/icons/open.svg
  src/assets/icons/search.svg
  src/assets/icons/unchecked.svg
  src/assets/icons/user.svg
  src/assets/images/home-image.svg
  src/assets/images/my-funding.svg
  src/assets/images/participated_funding.svg
  src/components/Calendar/index.tsx
  src/components/Card/index.tsx
  src/components/Card/styles.ts
  src/components/HeaderWithLogo/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/ProgressBar/index.tsx
  src/components/common/ProgressBar/styles.ts
  src/pages/funding/[id]/index.tsx
  src/pages/funding/create/1/index.tsx
  src/pages/funding/create/4/index.tsx
  src/pages/index.tsx
  src/pages/mypage/fundings/[types].tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/styles.ts
  src/pages/style.ts
  src/types/funding.ts
Labels: ✨ Feature

#28 [#27] Refactor: 약관 동의 컴포넌트화
  src/components/Layout/pageLayout/index.tsx
  src/components/TermsAndConditions/Terms.tsx
  src/components/TermsAndConditions/index.tsx
  src/components/TermsAndConditions/styles.ts
  src/constants/terms.tsx
  src/pages/funding/create/4/index.tsx
  src/pages/funding/create/styles.ts
Labels: ♻️ Refactor

#31 [#30] Feature: 로그인 API 및 펀딩 개설 API 연결
  src/components/HeaderWithLogo/index.tsx
  src/components/Layout/pageLayout/index.tsx
  src/components/common/Button/index.tsx
  src/hooks/queries/useAuth.ts
  src/hooks/queries/useCreateFunding.ts
  src/pages/funding/create/3/index.tsx
  src/pages/funding/create/4/index.tsx
  src/pages/index.tsx
  src/store/store.tsx
  src/store/types.ts
  src/types/auth.ts
Labels: ✨ Feature

#32 [#30] Feature: 펀딩 개설, 마이페이지 api 연결
  src/assets/icons/big-gift-image.svg
  src/assets/icons/user.svg
  src/components/HeaderWithLogo/index.tsx
  src/components/Layout/pageLayout/index.tsx
  src/hooks/queries/useAuth.ts
  src/hooks/queries/useGetFundingList.ts
  src/pages/funding/create/1/index.tsx
  src/pages/funding/create/4/index.tsx
  src/pages/index.tsx
  src/pages/mypage/fundings/[types].tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/styles.ts
Labels: ✨ Feature

#36 [#35] Feature: 서비스 둘러보기 UI 구현
  src/assets/images/funding_create_image.svg
  src/assets/images/funding_delivery_image.svg
  src/assets/images/funding_participate_image.svg
  src/assets/images/funding_target_image.svg
  src/components/Card/index.tsx
  src/components/Card/styles.ts
  src/pages/funding/create/4/index.tsx
  src/pages/index.tsx
  src/pages/style.ts
Labels: ✨ Feature

#38 [#37] Refactor: 로그인 모달 분리
  src/components/HeaderWithLogo/index.tsx
  src/components/modals/LoginModal/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/style.ts
Labels: ♻️ Refactor

#40 [#26] Feature: 카카오톡 공유하기 구현
  src/pages/_app.tsx
  src/pages/funding/create/2/index.tsx
  src/pages/funding/create/4/index.tsx
  src/pages/index.tsx
  src/types/env.d.ts
Labels: ✨ Feature

#43 [#41] Hotfix: 오류 수정
  .github/workflows/deploy.yml
  build.sh
  next.config.js
  package.json
  pnpm-lock.yaml
  src/components/Calendar/styles.ts
  src/components/Card/index.tsx
  src/components/Card/styles.ts
  src/components/FundingStatusBox/index.tsx
  src/components/FundingStatusBox/styles.ts
  src/components/HeaderWithLogo/index.tsx
  src/components/Layout/AuthRoot/index.tsx
  src/components/Layout/pageLayout/index.tsx
  src/components/Layout/styles.ts
  src/components/MessageList/MessageBox/styles.ts
  src/components/MessageList/styles.ts
  src/components/TermsAndConditions/index.tsx
  src/components/TermsAndConditions/styles.ts
  src/components/common/Button/index.tsx
  src/components/common/Button/styles.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/styles.ts
  src/components/common/Modal/styles.ts
  src/components/common/ProgressBar/index.tsx
  src/components/common/ProgressBar/styles.ts
  src/components/common/StatusTag/styles.ts
  src/components/modals/LoginModal/index.tsx
  src/components/modals/ModalWithIcon/styles.ts
  src/hooks/queries/useAuth.ts
  src/pages/_app.page.tsx
  src/pages/_document.page.tsx
  src/pages/funding/[id]/index.page.tsx
  src/pages/funding/[id]/participate/index.page.tsx
  src/pages/funding/[id]/participate/styles.ts
  src/pages/funding/[id]/payment/fail.page.tsx
  src/pages/funding/[id]/payment/index.page.tsx
  src/pages/funding/[id]/payment/styles.ts
  src/pages/funding/[id]/payment/success.page.tsx
  src/pages/funding/[id]/styles.ts
  src/pages/funding/create/1/index.page.tsx
  src/pages/funding/create/2/index.page.tsx
  src/pages/funding/create/3/index.page.tsx
  src/pages/funding/create/4/index.page.tsx
  src/pages/funding/create/styles.ts
  src/pages/index.page.tsx
  src/pages/invite/[id]/index.page.tsx
  src/pages/invite/[id]/styles.ts
  src/pages/mypage/fundings/[types].page.tsx
  src/pages/mypage/index.page.tsx
  src/pages/mypage/styles.ts
  src/pages/style.ts
  tsconfig.json
Labels: 🐛 BugFix

#45 [#33] Feature: refresh 토큰 api 연결
  package.json
  pnpm-lock.yaml
  src/hooks/queries/useAuth.ts
  src/pages/funding/[id]/index.page.tsx
  src/pages/index.page.tsx
  src/types/auth.ts
Labels: ✨ Feature
