Repository zip-up/zipup-frontend, pull requests merged in 2024-05, with the labels that each got.

#55 [#54] Bugfix: 펀딩 등록 관련 에러 수정
  src/components/common/Header/index.tsx
  src/pages/funding/[id]/index.page.tsx
  src/pages/funding/create/1/index.page.tsx
  src/pages/funding/create/2/index.page.tsx
  src/pages/funding/create/4/index.page.tsx
  src/pages/funding/create/styles.ts
Labels: 🐛 BugFix

#61 [#60] Refactor: 폰트 관련 문제 수정
  panda.config.ts
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/PretendardVariable.woff2
  src/components/Calendar/styles.ts
  src/components/Card/styles.ts
  src/components/FundingStatusBox/styles.ts
  src/components/MessageList/MessageBox/styles.ts
  src/components/MessageList/styles.ts
  src/components/Term/styles.ts
  src/components/common/Button/styles.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/styles.ts
  src/components/common/StatusTag/styles.ts
  src/components/modals/ModalWithIcon/styles.ts
  src/pages/404.page.tsx
  src/pages/_document.page.tsx
  src/pages/funding/[id]/participate/styles.ts
  src/pages/funding/[id]/payment/styles.ts
  src/pages/funding/[id]/styles.ts
  src/pages/funding/create/1/index.page.tsx
  src/pages/funding/create/4/index.page.tsx
  src/pages/funding/create/styles.ts
  src/pages/index.page.tsx
  src/pages/invite/[id]/styles.ts
  src/pages/login/styles.ts
  src/pages/mypage/styles.ts
  src/pages/style.ts
  src/styles/font.ts
  src/styles/textStyles.ts
Labels: ⚙️ Chore, ♻️ Refactor

#65 [#62] Feature: 회원탈퇴 구현 및 공통 버튼 스타일 리팩토링
  panda.config.ts
  public/fail.png
  src/assets/icons/checkbox/active.svg
  src/assets/icons/checkbox/disabled.svg
  src/assets/icons/checkbox/index.ts
  src/assets/icons/priceLabel/index.ts
  src/assets/icons/radio/active.svg
  src/assets/icons/radio/disabled.svg
  src/assets/icons/radio/index.ts
  src/components/Layout/NoticePageLayout/index.tsx
  src/components/Layout/NoticePageLayout/styles.ts
  src/components/Term/index.tsx
  src/components/common/Button/GradientBackground/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/styles.ts
  src/constants/notice.ts
  src/constants/terms.ts
  src/contexts/ReactQueryContext.tsx
  src/hooks/queries/useAuth.ts
  src/pages/funding/[id]/index.page.tsx
  src/pages/funding/[id]/participate/index.page.tsx
  src/pages/funding/[id]/participate/styles.ts
  src/pages/funding/create/1/index.page.tsx
  src/pages/funding/create/2/index.page.tsx
  src/pages/funding/create/4/index.page.tsx
  src/pages/funding/create/styles.ts
  src/pages/index.page.tsx
  src/pages/login/index.page.tsx
  src/pages/mypage/withdrawal/fail.page.tsx
  src/pages/mypage/withdrawal/index.page.tsx
  src/pages/mypage/withdrawal/styles.ts
  src/pages/mypage/withdrawal/success.page.tsx
  src/styles/textStyles.ts
Labels: ✨ Feature, ♻️ Refactor

#59 [#58] Feature: 자주 묻는 질문 페이지 구현
  src/components/Accordion/index.tsx
  src/components/Accordion/styles.ts
  src/components/Card/index.tsx
  src/components/Footer/index.tsx
  src/components/Footer/styles.ts
  src/components/HeaderWithLogo/index.tsx
  src/components/HeaderWithLogo/styles.ts
  src/components/Layout/index.tsx
  src/components/NoResult/index.tsx
  src/components/NoResult/styles.ts
  src/components/common/Header/index.tsx
  src/components/common/ProgressBar/index.tsx
  src/components/common/Spinner/styles.ts
  src/components/common/Tabs/index.tsx
  src/components/common/Tabs/style.ts
  src/components/modals/AddressModal/index.tsx
  src/constants/faqs.ts
  src/hooks/queries/useAuth.ts
  src/hooks/queries/useFundingList.ts
  src/pages/_document.page.tsx
  src/pages/faq/index.page.tsx
  src/pages/faq/styles.ts
  src/pages/funding/[id]/payment/success.page.tsx
  src/pages/funding/create/1/index.page.tsx
  src/pages/funding/create/2/index.page.tsx
  src/pages/funding/create/3/index.page.tsx
  src/pages/index.page.tsx
  src/pages/mypage/fundings/[types].page.tsx
  src/pages/mypage/index.page.tsx
  src/pages/mypage/styles.ts
Labels: ✨ Feature

#69 [#64] Feature: 서비스 둘러보기 페이지 구현
  public/home-fragment-hand.png
  public/home-image.png
  public/home.png
  src/assets/icons/go.svg
  src/assets/images/home-fragment-brick.svg
  src/components/Accordion/index.tsx
  src/components/Card/index.tsx
  src/components/Card/styles.ts
  src/components/Footer/index.tsx
  src/components/HeaderWithLogo/index.tsx
  src/components/HeaderWithLogo/styles.ts
  src/components/MyFundings/index.page.tsx
  src/components/MyFundings/styles.ts
  src/components/common/Button/index.tsx
  src/components/common/Button/styles.ts
  src/components/common/Modal/styles.ts
  src/components/common/StatusTag/styles.ts
  src/components/common/Tabs/index.tsx
  src/components/modals/AddressModal/index.tsx
  src/hooks/queries/useAuth.ts
  src/hooks/queries/useFundingList.ts
  src/pages/funding/create/1/index.page.tsx
  src/pages/funding/create/2/index.page.tsx
  src/pages/index.page.tsx
  src/pages/mypage/fundings/[types].page.tsx
  src/pages/mypage/index.page.tsx
  src/pages/mypage/styles.ts
  src/pages/style.ts
  src/pages/trending/index.page.tsx
  src/store/store.ts
  src/types/funding.ts
Labels: ✨ Feature

#70 [#66] Feature: 결제 내역 페이지 및 취소 및 펀딩 삭제 작업
  panda.config.ts
  public/default-funding-80.png
  src/assets/icons/cancel.svg
  src/assets/icons/delete-menu.svg
  src/assets/icons/delete.svg
  src/assets/icons/dropdown-btn.svg
  src/assets/icons/edit-note.svg
  src/assets/icons/more-btn-clicked.svg
  src/assets/icons/more-btn.svg
  src/assets/icons/upload.svg
  src/components/NoResult/index.tsx
  src/components/PaymentCard/index.tsx
  src/components/PaymentCard/styles.ts
  src/components/common/Button/GradientBackground/index.tsx
  src/components/common/Button/styles.ts
  src/components/common/DropDown/index.tsx
  src/components/common/DropDown/styles.ts
  src/components/common/Menu/index.tsx
  src/components/common/Menu/styles.ts
  src/components/common/Modal/index.tsx
  src/components/common/Modal/styles.ts
  src/components/common/RadioSelector/index.tsx
  src/components/common/RadioSelector/styles.ts
  src/components/modals/AddressModal/index.tsx
  src/components/modals/ModalActionButtons/index.tsx
  src/components/modals/ModalWithIcon/index.tsx
  src/constants/bank.ts
  src/constants/notice.ts
  src/constants/tabs.ts
  src/hooks/queries/useAuth.ts
  src/hooks/queries/useFunding.ts
  src/hooks/queries/usePayment.ts
  src/pages/funding/[id]/index.page.tsx
  src/pages/funding/[id]/participate/index.page.tsx
  src/pages/funding/[id]/participate/styles.ts
  src/pages/funding/[id]/payment/index.page.tsx
  src/pages/funding/[id]/styles.ts
  src/pages/mypage/payinfo/index.page.tsx
  src/pages/mypage/payinfo/styles.ts
  src/styles/globals.css
  src/types/funding.ts
  src/utils/date.ts
Labels: ✨ Feature

#68 [#67] Feature: 모달 표시 시 화면 고정 기능 구현
  src/components/Footer/index.tsx
  src/components/common/Modal/index.tsx
  src/components/modals/ModalWithIcon/index.tsx
  src/hooks/useLockScroll.tsx
  src/pages/funding/create/1/index.page.tsx
  src/pages/funding/create/4/index.page.tsx
  src/pages/index.page.tsx
  src/pages/mypage/fundings/[types].page.tsx
  src/pages/style.ts
Labels: ✨ Feature

#73 [#72] Fix: SSR환경에서 헤더에 쿠키가 담기지 않는 이슈 해결
  src/api/index.ts
  src/components/modals/ModalWithIcon/index.tsx
  src/pages/funding/[id]/payment/success.page.tsx
  src/pages/invite/[id]/index.page.tsx
Labels: 🐛 BugFix

#76 [#74] Feature: 페이지 연결 및 잘못된 스타일 수정
  src/components/Accordion/index.tsx
  src/components/Accordion/styles.ts
  src/components/Footer/index.tsx
  src/components/PaymentCard/index.tsx
  src/components/PaymentCard/styles.ts
  src/components/ServiceCard/index.tsx
  src/components/ServiceCard/styles.ts
  src/components/common/StatusTag/styles.ts
  src/components/common/Tabs/style.ts
  src/hooks/queries/usePayment.ts
  src/pages/funding/[id]/participate/styles.ts
  src/pages/funding/[id]/payment/fail.page.tsx
  src/pages/funding/[id]/payment/styles.ts
  src/pages/funding/[id]/payment/success.page.tsx
  src/pages/mypage/index.page.tsx
  src/pages/mypage/payinfo/index.page.tsx
  src/pages/mypage/payinfo/styles.ts
  src/pages/mypage/styles.ts
Labels: ✨ Feature, ♻️ Refactor

#79 [#78] Fix: 결제 취소 후 데이터 갱신 및 전역 에러 핸들링
  public/error.png
  src/components/CustomError/index.tsx
  src/components/common/Menu/index.tsx
  src/components/modals/ModalActionButtons/index.tsx
  src/constants/apiError.ts
  src/contexts/ReactQueryContext.tsx
  src/hooks/queries/usePayment.ts
  src/pages/404.page.tsx
  src/pages/500.page.tsx
  src/pages/funding/[id]/index.page.tsx
  src/pages/funding/create/1/index.page.tsx
  src/pages/funding/create/4/index.page.tsx
  src/pages/index.page.tsx
  src/pages/mypage/payinfo/index.page.tsx
  src/pages/mypage/withdrawal/index.page.tsx
Labels: 🐛 BugFix, ✨ Feature

#77 [#75] 인기 펀딩 API 연결
  src/components/MyFundings/index.page.tsx
  src/hooks/queries/useFundingList.ts
  src/pages/index.page.tsx
  src/pages/mypage/fundings/[types].page.tsx
  src/pages/trending/index.page.tsx
Labels: ✨ Feature

#82 [#71] Fix: 탭 UI 수정
  src/components/common/Tabs/index.tsx
  src/components/common/Tabs/style.ts
Labels: 🐛 BugFix
